# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c779b1c30bca777900d05ad38a57a0604d76c4f1b041c84946fcf273851f66fc1577d357c599b5c588d8b579716459c68f6cc4d7047756836ef730e5212f99eb

test:
  secret_key_base: c4486e41f2c3acefca1bd2979865579911b37469f728112692a952e6c124faae1ee0fb6e5370a9d0fd285e1ae4f2fab422d2f159eb94e523ab7cd8f209085042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
